# Generated by Django 6.0.5 on 2026-05-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('organizer', 'Organizer'), ('manager', 'Manager')], default='customer', max_length=20),
        ),
    ]
